version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    entrypoint: ./entry-point.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - ./chroma-persistent-data/db:/chroma/chroma
volumes:
  chroma-data:
    driver: local